package model.bean;
// Generated 2016/1/11 �U�� 06:10:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CollectId generated by hbm2java
 */
@Embeddable
public class CollectId implements java.io.Serializable {

	private int memberId;
	private int sceneId;

	public CollectId() {
	}

	public CollectId(int memberId, int sceneId) {
		this.memberId = memberId;
		this.sceneId = sceneId;
	}

	@Column(name = "MemberID", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "SceneID", nullable = false)
	public int getSceneId() {
		return this.sceneId;
	}

	public void setSceneId(int sceneId) {
		this.sceneId = sceneId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CollectId))
			return false;
		CollectId castOther = (CollectId) other;

		return (this.getMemberId() == castOther.getMemberId()) && (this.getSceneId() == castOther.getSceneId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberId();
		result = 37 * result + this.getSceneId();
		return result;
	}

}
