package model.bean;
// Generated 2016/1/11 �U�� 06:10:10 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Collect generated by hbm2java
 */
@Entity
@Table(name = "Collect", schema = "dbo", catalog = "travel")
public class Collect implements java.io.Serializable {

	private CollectId id;
	private Member member;
	private Scene scene;
	private Integer collectId;

	public Collect() {
	}

	public Collect(CollectId id, Member member, Scene scene) {
		this.id = id;
		this.member = member;
		this.scene = scene;
	}

	public Collect(CollectId id, Member member, Scene scene, Integer collectId) {
		this.id = id;
		this.member = member;
		this.scene = scene;
		this.collectId = collectId;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "memberId", column = @Column(name = "MemberID", nullable = false) ),
			@AttributeOverride(name = "sceneId", column = @Column(name = "SceneID", nullable = false) ) })
	public CollectId getId() {
		return this.id;
	}

	public void setId(CollectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MemberID", nullable = false, insertable = false, updatable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SceneID", nullable = false, insertable = false, updatable = false)
	public Scene getScene() {
		return this.scene;
	}

	public void setScene(Scene scene) {
		this.scene = scene;
	}

	@Column(name = "CollectID")
	public Integer getCollectId() {
		return this.collectId;
	}

	public void setCollectId(Integer collectId) {
		this.collectId = collectId;
	}

}
