package model.bean;
// Generated 2016/1/11 �U�� 06:10:10 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Scene generated by hbm2java
 */
@Entity
@Table(name = "Scene", schema = "dbo", catalog = "travel")
public class Scene implements java.io.Serializable {

	private int sceneId;
	private Member member;
	private String location;
	private String city;
	private String sceneName;
	private byte[] scenePhoto;
	private String sceneContent;
	private String timeStart;
	private String timeEnd;
	private Set<Collect> collects = new HashSet<Collect>(0);

	public Scene() {
	}

	public Scene(int sceneId, String sceneName) {
		this.sceneId = sceneId;
		this.sceneName = sceneName;
	}

	public Scene(int sceneId, Member member, String location, String city, String sceneName, byte[] scenePhoto,
			String sceneContent, String timeStart, String timeEnd, Set<Collect> collects) {
		this.sceneId = sceneId;
		this.member = member;
		this.location = location;
		this.city = city;
		this.sceneName = sceneName;
		this.scenePhoto = scenePhoto;
		this.sceneContent = sceneContent;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.collects = collects;
	}

	@Id

	@Column(name = "SceneID", unique = true, nullable = false)
	public int getSceneId() {
		return this.sceneId;
	}

	public void setSceneId(int sceneId) {
		this.sceneId = sceneId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MemberID")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "Location", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "City", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "SceneName", nullable = false, length = 50)
	public String getSceneName() {
		return this.sceneName;
	}

	public void setSceneName(String sceneName) {
		this.sceneName = sceneName;
	}

	@Column(name = "ScenePhoto")
	public byte[] getScenePhoto() {
		return this.scenePhoto;
	}

	public void setScenePhoto(byte[] scenePhoto) {
		this.scenePhoto = scenePhoto;
	}

	@Column(name = "SceneContent", length = 8000)
	public String getSceneContent() {
		return this.sceneContent;
	}

	public void setSceneContent(String sceneContent) {
		this.sceneContent = sceneContent;
	}

	@Column(name = "TimeStart", length = 50)
	public String getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}

	@Column(name = "TimeEnd", length = 50)
	public String getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(String timeEnd) {
		this.timeEnd = timeEnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scene")
	public Set<Collect> getCollects() {
		return this.collects;
	}

	public void setCollects(Set<Collect> collects) {
		this.collects = collects;
	}

}
